### ISSUE TITLE
The the bug who crash the server every few hour!

### ISSUE THREAD

**Issue by sylphio** [sylphio/Sebcyn-MC-issues#93]
Potential cause candidate: Buildcraft & opencomputer

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at net.minecraft.world.World.func_72939_s(World.java:1933)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by sylphio** [comment]
Fixé par l'update de buildcraft
